title: Imtiaz's Tech Journey
description: >- # this means to ignore newlines until "theme:"
  Welcome to my portfolio! I'm a seasoned software engineer
  with over a decade of experience in a diverse range of technologies, including Java, JavaScript, Python and C++, 
  leveraging my extensive hands-on experience to deliver innovative solutions.
  Explore my projects, contributions, and expertise in building robust and scalable applications.
theme: jekyll-theme-midnight